// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urdwcaiadrcihivvatel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZHdjYWlhZHJjaWhpdnZhdGVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODU4NzQsImV4cCI6MjA1ODU2MTg3NH0.a3Cl2d2YQoMAJbD_2ky7koQ9bfoDYuQsSfnsIp6RYWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);